# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
# 
# gamma 6 MeV to the direction (0.,-1,0)
#
/gun/particle gamma
/gun/energy 6 MeV
#
/run/beamOn 100000
# 







